# Generated by Django 2.1.1 on 2019-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
