# Generated by Django 2.1.1 on 2019-09-22 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20190922_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
